# Generated by Django 5.1.3 on 2024-12-06 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id_membresia', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250)),
                ('cantidad', models.IntegerField()),
                ('tiempo_vigen', models.CharField(max_length=50)),
                ('precio_membre', models.FloatField()),
                ('descuento', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
            ],
        ),
    ]
