# Generated by Django 5.1.3 on 2024-12-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos_app', '0002_rename_mantenimiento_articulo_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='fecha_crea',
            field=models.CharField(max_length=50),
        ),
    ]
