# Generated by Django 5.1.3 on 2024-12-06 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id_local', models.IntegerField(primary_key=True, serialize=False)),
                ('ubicacion', models.CharField(max_length=250)),
                ('anos_funcio', models.IntegerField()),
                ('horario', models.CharField(max_length=50)),
                ('tamano', models.CharField(max_length=50)),
                ('dueno', models.CharField(max_length=150)),
                ('empleados_total', models.IntegerField()),
            ],
        ),
    ]
