# Generated by Django 5.1.3 on 2024-12-06 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_entrada', models.DateField()),
                ('tiempo_local', models.TimeField()),
                ('compra', models.CharField(max_length=50)),
                ('id_membresia', models.IntegerField()),
                ('metodo_pago', models.CharField(max_length=50)),
                ('calificacion_dada', models.CharField(max_length=50)),
            ],
        ),
    ]
