# Generated by Django 5.1.3 on 2024-12-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_app', '0006_alter_cliente_id_membresia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tiempo_local',
            field=models.CharField(max_length=50),
        ),
    ]
